### ISSUE TITLE
[Question] How do these shops works? More detailed explanation, please?

### ISSUE THREAD

**Issue by MaranRoseGIT** [IAmSneak/diamond-chestshop#10]
Latest Version of Diamond Economy and Chest Shops, and players are very much confused on how the chestshops actually function, they have set them up completely properly and items are hovering above the chests, but they can't buy.... or sell anything. It's doing literally nothing, and players are absolutely confused, and I am too.

**_Minecraft Fabric 1.18.2_**

**Comment by IAmSneak** [comment]
as discussed on the discord its definitely due to the capitalization restriction on my part
