### ISSUE TITLE
[Suggestion] Admin shops

### ISSUE THREAD

**Issue by itzLukeYo** [IAmSneak/diamond-chestshop#15]
Hi! It would be great if there was a way we could set up an admin shop, where the shop could just dupe you new items so we wouldn't have to re-stock the chests with command blocks and hoppers.

**Comment by IAmSneak** [comment]
this is already possible by clicking the sign with a command block

**Comment by itzLukeYo** [comment]
Thanks for letting me know! Some documentation about this would be nice though. Unless I am simply blind and missed it.
