### ISSUE TITLE
Chest shops can have items taken out by hoppers

### ISSUE THREAD

**Issue by Krambed** [IAmSneak/diamond-chestshop#4]
title

**Comment by Krambed** [comment]
my suggestion would be to have settings for both having hoppers putting items in and taking them out (for farm locking)

**Comment by IAmSneak** [comment]
I decided not to do this at some point but I'm unsure why. I think the hopper owner is already stored in the hopper so it should be really easy.

**Comment by IAmSneak** [comment]
it is in the latest curseforge release
