### ISSUE TITLE
[Bug] Chestshop signs appear blank when broken by non-owners, resets when traveling dimensions.

### ISSUE THREAD

**Issue by MaranRoseGIT** [IAmSneak/diamond-chestshop#5]
Video explaining the bug: https://www.youtube.com/watch?v=OzqLTeAa_8M

The only other bug I found is an incompatibility with Charm's "EditableSigns" feature which won't let users buy/sell items on a chestshop with their empty hand, I'm unsure if you could make a work-around with that? If you need more details with that, I will provide.

_**Minecraft Fabric 1.18.2**_

**Comment by MaranRoseGIT** [comment]
Is this marked as completed/fixed?

**Comment by IAmSneak** [comment]
It should be fixed in the latest release as well as improved mod compat. I tested it with charm and that definitely works.
